- hosts: all
  gather_facts: 0
  vars_files:
  - vars/subnets.yml
  - vars/main.yml
  vars:
    username:   "{{ lookup('evn',) }}"
    password:   "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
  roles:
  - role: redhat.satellite.organizations
    tags: organizations
  #- role: redhat.satellite.locations
  #  tags: locations
  - role: redhat.satellite.subnets
    tags: subnets
  - role: redhat.satellite.provisioning_templates
    tags: provisioning_templates
    vars:
      satellite_provisioning_templates:
      - name: Compliance Kickstart default
        state:  present
        template: "{{ lookup('template', 'compliance_kickstart_default.erb.j2') }}"