- name: "Sync repository"
  redhat.satellite.repository_sync:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ item.organization | default(omit) }}"
    location: "{{ item.location | default(omit) }}"
    product: "{{ item.product }}"
    repository: "{{ item.repository }}"
  with_items: "{{ satellite_repository_sync | default([]) }}"