---

- name: Create web directories
  file:
    path:  "{{ item.web_path }}"
    state: directory
    owner: foreman
    group: foreman
    mode: 755
  with_items: "{{ zips_to_unarchive | default([]) }}"

- name: Create unarchive directories
  file:
    path:  "{{ item.unarchive_path }}"
    state: directory
    mode: 755
  with_items: "{{ zips_to_unarchive | default([]) }}"

- name: unarchive zip content
  unarchive:
    src:  "{{ item.zip_path }}"
    dest: "{{ item.unarchive_path }}"
    remote_src: true
  with_items: "{{ zips_to_unarchive | default([]) }}"

- name: Synchronize ISO contents to web directory
  ansible.posix.synchronize:
    src: "{{ item.unarchive_path }}/"
    dest: "{{ item.web_path }}"
    delete: true
    recursive: true 
  with_items: "{{ zips_to_unarchive | default([]) }}"
  delegate_to: "{{ ansible_fqdn }}"

- name: Create YUM repository metadata
  command: "createrepo {{ item.web_path }}"
  with_items: "{{ zips_to_unarchive | default([]) }}"