---
- name: Create locations 
  custom_location:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default('false') }}"
    name: "{{ item.name }}"
    parent: "{{ item.parent | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    smart_proxies: "{{ item.smart_proxies | default(omit) }}"
    parameters: "{{ item.parameters | default(omit) }}"
  loop: "{{ satellite_locations }}"