- name: create new installation medium
  redhat.satellite.installation_medium:
    username:   "{{ satellite_username | default(omit) }}"
    password:   "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    name: "{{ item.name }}"
    locations: "{{ item.locations | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    operatingsystems: "{{ item.operatingsystems | default(omit) }}"
    path: "{{ item.path }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ satellite_installation_mediums | default(omit) }}"