- name: "Create a Partition Template from a file and modify with parameter(s)"
  redhat.satellite.partition_table:
    username:   "{{ satellite_username | default(omit) }}"
    password:   "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    layout: "{{ item.layout | default(omit) }}"
    name:   "{{ item.name }}"
    locked: "{{ item.locked | default(omit) }}"
    state:  "{{ item.state | default('present') }}"
    locations:    "{{ item.location | default(omit) }}"
    organization: "{{ item.organization | default(omit) }}"
    os_family: "{{ item.os_family | default(omit) }}"
  with_items:  "{{ satellite_partition_table | default([]) }}"