secret_root: redhat88
grub_root_hash: grub.pbkdf2.sha512.10000.210902A80962E17BA2F7677D8B9D9DAD1CCA496FCAE3F6D52AB84AD6B141B43FB79F92F7648BC2FA51B9D8E92C745CEA0C13E9BF4A60C752E8D33A690AD47038.A613E17142E0286AB7DE162DC4DADCA2E400896196FF083AEE401091BF83F01E5D9C78E3B5740FDBE569DC590B5D03FAD9EF87097657B3F991A656AE59CF0F05 
satellite_location: hallas
satellite_hostname: satellite.lou.land
satellite_server_url: https://satellite.lou.land
satellite_username: admin
satellite_password: redhat
satellite_organization:   hallas
vm_template_web_path: "/var/www/html/pub/vm-templates"
satellite_validate_certs: "{{ validate_certs | default('true') }}"


isos_to_mount:
- mount_path: /mnt/OEL87
  iso_location: /home/OEL87.iso
  web_path: /var/www/html/pub/OEL87-KS
#isos8_to_mount:
#- mount_path: /mnt/OEL87
  #iso_location: /home/OEL87.iso
  #pulp_path:
  #- /var/www/html/pub/OEL87-BAS-KS 
  #- /var/www/html/pub/OEL87-APP-KS 
  #web_path:
  #- web_path: /var/www/html/pub/OEL87-BAS-KS
  #  source:   /mnt/OEL87/BaseOS
  #- web_path: /var/www/html/pub/OEL87-APP-KS
  #  source:   /mnt/OEL87/AppStream
  #- web_path: /var/www/html/pub/OEL87-BAS-KS
  #  source:   /mnt/OEL87/EULA
  #- web_path: /var/www/html/pub/OEL87-BAS-KS
  #  source:   /mnt/OEL87/GPL
  #- web_path: /var/www/html/pub/OEL87-BAS-KS/images
  #  source:   /mnt/OEL87/images

satellite_installation_mediums:
- name: OracleLinux8.7
  path: "http://{{ satellite_hostname }}/pulp/content/hallas/Library/custom/OEL-KS/OEL87"
  
satellite_products: 
- name: vmware-templates
  repositories:
  - name: vm-templates
    content_type: file
    unprotected: true
    verify_ssl_on_sync: false
    url: "{{ satellite_server_url }}/pub/vm-templates"
- name: 'OEL-KS'
  repositories:
  - name: OEL87-KS
    content_type: file
    unprotected: true
    verify_ssl_on_sync: false
    url: "{{ satellite_server_url }}/pub/OEL87-KS"
#- name: 'OEL-KS'
#  repositories:
#  - name: OEL87-BAS-KS
#    content_type: file
#    unprotected: true
#    verify_ssl_on_sync: false
#    url: "{{ satellite_server_url }}/pub/OEL87-BAS-KS"
#  repositories:
#  - name: OEL87-APP-KS
#    content_type: file
#    unprotected: true
#    verify_ssl_on_sync: false
#    url: "{{ satellite_server_url }}/pub/OEL87-APP-KS" 

satellite_repository_sync:
- product: OEL-KS
  repository: OEL87-KS
  organization: "{{ satellite_organization }}"

satellite_content_views:
- name: OEL-KS
  repositories:
  - name: OEL87-KS
    product: OEL-KS
  - name: OEL79-KS
    product: OEL-KS
  - name: OEL69-KS
    product: OEL-KS
- name: RHEL-KS
  repositories:
  - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.8'
    product: 'Red Hat Enterprise Linux for x86_64'
  - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'
    product: 'Red Hat Enterprise Linux for x86_64'
  - name: 'Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9'
    product: 'Red Hat Enterprise Linux Server'
- name: kickstart
  components:
  - content_view: OEL-KS
    latest: true
  - content_view: RHEL-KS
    latest: true

satellite_locations:
- name: hallas

satellite_architecture:
- name: x86_64

satellite_operatingsystems:
- name:  "KS-RedHat"
  major: "8"
  minor: "8"
  os_family: "Redhat"
  password_hash: SHA256
  architectures: x86_64
  ptables: DISA STIG Kickstart Disk Layout
  default_templates:
  - template_kind: "provision"
    provisioning_template: "Compliance Kickstart default"
  - template_kind: "PXELinux"
    provisioning_template: "Kickstart default PXELinux"
  - template_kind: "iPXE"
    provisioning_template: "Kickstart default iPXE"
  - template_kind: "PXEGrub"
    provisioning_template: "Kickstart default PXEGrub"
  - template_kind: "PXEGrub2"
    provisioning_template: "Kickstart default PXEGrub2"
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "host_init_config"
    state:  absent
  - template_kind: "kexec"
    state:  absent
  - template_kind: "user_data"
    state:  absent
- name:  "KS-RedHat"
  major: "7"
  minor: "9"
  os_family: "Redhat"
  password_hash: "SHA256"
  architectures: "x86_64"
  ptables: "DISA STIG Kickstart Disk Layout"
  default_templates:
  - template_kind: "provision"
    provisioning_template: "Compliance Kickstart default"
  - template_kind: "PXELinux"
    provisioning_template: "Kickstart default PXELinux"
  - template_kind: "iPXE"
    provisioning_template: "Kickstart default iPXE"
  - template_kind: "PXEGrub"
    provisioning_template: "Kickstart default PXEGrub"
  - template_kind: "PXEGrub2"
    provisioning_template: "Kickstart default PXEGrub2"
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "host_init_config"
    state:  absent
  - template_kind: "kexec"
    state:  absent
  - template_kind: "user_data"
    state:  absent
- name:  "KS-OracleLinux"
  major: "8"
  minor: "7"
  os_family: "Redhat"
  password_hash: "SHA256"
  architectures: "x86_64"
  ptables: "DISA STIG Kickstart Disk Layout"
  media: OracleLinux8.7
  default_templates:
  - template_kind: "provision"
    provisioning_template: "Compliance Kickstart default"
  - template_kind: "PXELinux"
    provisioning_template: "Kickstart default PXELinux"
  - template_kind: "iPXE"
    provisioning_template: "Kickstart default iPXE"
  - template_kind: "PXEGrub"
    provisioning_template: "Kickstart default PXEGrub"
  - template_kind: "PXEGrub2"
    provisioning_template: "Kickstart default PXEGrub2"
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "host_init_config"
    state:  absent
  - template_kind: "kexec"
    state:  absent
  - template_kind: "user_data"
    state:  absent
- name:  "KS-OracleLinux"
  major: "7"
  minor: "9"
  os_family: "Redhat"
  password_hash: "SHA256"
  architectures: "x86_64"
  ptables: "DISA STIG Kickstart Disk Layout"
  media: OracleLinux7.9
  default_templates:
  - template_kind: "provision"
    provisioning_template: "Compliance Kickstart default"
  - template_kind: "PXELinux"
    provisioning_template: "Kickstart default PXELinux"
  - template_kind: "iPXE"
    provisioning_template: "Kickstart default iPXE"
  - template_kind: "PXEGrub"
    provisioning_template: "Kickstart default PXEGrub"
  - template_kind: "PXEGrub2"
    provisioning_template: "Kickstart default PXEGrub2"
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "host_init_config"
    state:  absent
  - template_kind: "kexec"
    state:  absent
  - template_kind: "user_data"
    state:  absent
- name:  "KS-OracleLinux"
  major: "6"
  minor: "9"
  os_family: "Redhat"
  password_hash: "SHA256"
  architectures: "x86_64"
  ptables: "DISA STIG Kickstart Disk Layout"
  media: "OracleLinux6.9"
  default_templates:
  - template_kind: "provision"
    provisioning_template: "Compliance Kickstart default"
  - template_kind: "PXELinux"
    provisioning_template: "Kickstart default PXELinux"
  - template_kind: "iPXE"
    provisioning_template: "Kickstart default iPXE"
  - template_kind: "PXEGrub"
    provisioning_template: "Kickstart default PXEGrub"
  - template_kind: "PXEGrub2"
    provisioning_template: "Kickstart default PXEGrub2"
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "host_init_config"
    state:  absent
  - template_kind: "kexec"
    state:  absent
  - template_kind: "user_data"
    state:  absent

satellite_hostgroups:
- name: 00-Template-Maker
  lifecycle_environment: Library
  organization: hallas
  openscap_proxy: satellite.lou.land
  content_source: satellite.lou.land
  compute_resource:  VMware
  pxe_loader: "PXELinux BIOS"
  architecture: x86_64
  content_view: library
  activation_keys: library
  ptable: DISA STIG Kickstart Disk Layout 
  root_pass: "{{ secret_root }}"
  domain: lou.land
  subnet: 192.168.2.0
  parameters:
  - name: use_ntp
    value: false
  - name: fips_enabled
    value: true
  - name: package_upgrade
    value: true
  - name: puppet_enabled
    value: false
  - name: remote_execution_create_user
    value: true
  - name: host_registration_insights
    value: false
  - name: satellite_user
    value: dossatellite
  - name: root_size
    value: 4096
  - name: swap_size
    value: 4096
  - name: vg_name
    value: my_vgnam
- name: RH7-Template-Maker
  parent: 00-Template-Maker
  compute_profile: Rh7-Template-Maker
  operatingsystem: KS-RedHat 7.9
  organization: hallas
  kickstart_repository: Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9
  parameters:
  - name: packages
    value: sssd,wget,yum-utils
- name: RH8-Template-Maker
  parent: 00-Template-Maker
  compute_profile: Rh8-Template-Maker
  organization: hallas
  kickstart_repository: Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8
  operatingsystem: KS-RedHat 8.8
  parameters:
  - name: packages
    value: sssd,wget,dnf-utils
  - name: disa_stig
    value: True
- name: OL8-Template-Maker
  parent: 00-Template-Maker
  compute_profile: Ol8-Template-Maker
  operatingsystem: KS-OracleLinux 8.7 
  architecture: x86_64
  medium: OracleLinux8.7
  parameters:
  - name: packages
    value: sssd,wget,yum-utils
- name: OL7-Template-Maker
  parent: 00-Template-Maker
  compute_profile: Ol7-Template-Maker
  operatingsystem: KS-OracleLinux 7.9 
  architecture: x86_64
  medium: OracleLinux7.9
  parameters:
  - name: packages
    value: sssd,wget,yum-utils
- name: OL6-Template-Maker
  parent: 00-Template-Maker
  compute_profile: Ol6-Template-Maker
  operatingsystem: KS-OracleLinux 6.9
  medium: OracleLinux6.9 
  parameters:
  - name: part_fstype
    value: ext4
  - name: packages
    value: sssd,wget,yum-utils

satellite_provisioning_templates:
- name: Compliance Kickstart default custom packages
  template: "{{ lookup('template', 'compliance_kickstart_default_custom_packages.erb.j2') }}"
  operatingsystems:
  - KS-Redhat 7.9
  - KS-Redhat 8.8
  - KS-OracleLinux 8.7
  - KS-OracleLinux 7.9
  - KS-OracleLinux 6.9
- name: Compliance Kickstart default
  template: "{{ lookup('template', 'compliance_kickstart_default.erb.j2') }}"
  operatingsystems:
  - KS-Redhat 7.9
  - KS-Redhat 8.8
  - KS-OracleLinux 8.7
  - KS-OracleLinux 7.9
  - KS-OracleLinux 6.9

- name: Compliance Kickstart default satellite user
  template: "{{ lookup('template', 'compliance_kickstart_default_satellite_user.erb.j2') }}"
  operatingsystems:
  - KS-Redhat 7.9
  - KS-Redhat 8.8
  - KS-OracleLinux 8.7
  - KS-OracleLinux 7.9
  - KS-OracleLinux 6.9
- name: Compliance Kickstart default custom post
  template: "{{ lookup('template', 'compliance_kickstart_default_custom_post.erb.j2') }}"
  operatingsystems:
  - KS-Redhat 7.9
  - KS-Redhat 8.8
  - KS-OracleLinux 8.7
  - KS-OracleLinux 7.9
  - KS-OracleLinux 6.9
satellite_partition_table:
- name: DISA STIG Disk Layout
  layout: "{{ lookup('template', 'disa_stig_kickstart_disk_layout.erb.j2') }}"
  os_family: Redhat

# This was done to avoid passwork leak
satellite_compute_resources:
  name: "VMware"
  provider: "vmware"
  provider_params:
    url: "vcenter.lou.land"
    user: "administrator@lou.land"
    password: "redhat"
    datacenter: "TNDC"

satellite_subnets:
  - name: 192.168.2.0
    description: "Created to KS VM Templates"
    network: "192.168.2.0"
    mask: "255.255.255.0"
    ipam: "None"
    gateway: "192.168.2.1"
    boot_mode: "Static"
    domains: "lou.land"
    organizations: hallas
    locations: hallas
    parameters:
    - name: vcenter
      value: vcenter.lou.land
    - name: datacenter
      value: TNDC
    - name: cluster
      value: TNCL
    - name: network
      value: "VM Network"

satellite_compute_profiles:
- name: "Rh8-Template-Maker"
  compute_attributes:
  - compute_resource: "VMware"
    vm_attrs:
      cluster: "TNCL"
      add_cdrom: True
      firmware: efi
      path: /Datacenters/TNDC/vm/test_folder
      memoryHotAddEnabled: true
      cpuHotAddEnabled: true
      folder_name: test_folder
      cpus: 2
      guest_id: rhel8_64Guest
      corespersocket: 1
      memory_mb: 8192
      add_cdrom: True
      boot_order: 
      - cdrom
      volumes_attributes:
        0:
          datastore: "cloud (1)"
          size_gb: 75
      interfaces_attributes:
        0:
          type: "VirtualVmxnet3"
          network: "VM Network"
- name: "Rh7-Template-Maker"
  compute_attributes:
  - compute_resource: "VMware"
    vm_attrs:
      cluster: "TNCL"
      add_cdrom: True
      firmware: efi
      path: /Datacenters/TNDC/vm/test_folder
      memoryHotAddEnabled: true
      cpuHotAddEnabled: true
      cpus: 2
      guest_id: rhel7_64Guest
      corespersocket: 1
      memory_mb: 8192
      volumes_attributes:
        0:
          datastore: "cloud (1)"
          size_gb: 75
      interfaces_attributes:
        0:
          type: "VirtualVmxnet3"
          network: "VM Network"
- name: "Ol8-Template-Maker"
  compute_attributes:
  - compute_resource: "VMware"
    vm_attrs:
      cluster: "TNCL"
      add_cdrom: True
      firmware: efi
      path: /Datacenters/TNDC/vm/test_folder
      memoryHotAddEnabled: true
      cpuHotAddEnabled: true
      cpus: 2
      guest_id: oracleLinux8_64Guest
      corespersocket: 1
      memory_mb: 8192
      add_cdrom: True
      boot_order: 
      - cdrom
      volumes_attributes:
        0:
          datastore: "cloud (1)"
          size_gb: 75
      interfaces_attributes:
        0:
          type: "VirtualVmxnet3"
          network: "VM Network"
- name: "Ol7-Template-Maker"
  compute_attributes:
  - compute_resource: "VMware"
    vm_attrs:
      cluster: "TNCL"
      add_cdrom: True
      firmware: efi
      path: /Datacenters/TNDC/vm/test_folder
      memoryHotAddEnabled: true
      cpuHotAddEnabled: true
      cpus: 2
      guest_id: oracleLinux7_64Guest
      corespersocket: 1
      memory_mb: 8192
      add_cdrom: True
      boot_order: 
      - cdrom
      volumes_attributes:
        0:
          datastore: "cloud (1)"
          size_gb: 75
      interfaces_attributes:
        0:
          type: "VirtualVmxnet3"
          network: "VM Network"
- name: "Ol6-Template-Maker"
  compute_attributes:
  - compute_resource: "VMware"
    vm_attrs:
      cluster: "TNCL"
      add_cdrom: True
      firmware: efi
      path: /Datacenters/TNDC/vm/test_folder
      memoryHotAddEnabled: true
      cpuHotAddEnabled: true
      cpus: 2
      guest_id: oracleLinux6_64Guest
      corespersocket: 1
      memory_mb: 8192
      add_cdrom: True
      boot_order: 
      - cdrom
      volumes_attributes:
        0:
          datastore: "cloud (1)"
          size_gb: 75
      interfaces_attributes:
        0:
          type: "VirtualVmxnet3"
          network: "VM Network"